//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductMaterials.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImagePath
    {
        public string Image1Path { get; set; }
        public string Image2Path { get; set; }
        public string Image3Path { get; set; }
        public string Image4Path { get; set; }
        public string Image5Path { get; set; }
        public string Image1Orig { get; set; }
        public string Image2Orig { get; set; }
        public string Image3Orig { get; set; }
        public string Image4Orig { get; set; }
        public string Image5Orig { get; set; }
        public string ImageProdNum { get; set; }
        public string ImageCompany { get; set; }
    }
}
