//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductMaterials.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class ProductMaterialEntities : DbContext
    {
        public ProductMaterialEntities()
            : base("name=ProductMaterialEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<product> products { get; set; }
        public DbSet<ProductImagePath> ProductImagePaths { get; set; }
    
        public virtual ObjectResult<sp_returnProducts_Result> sp_returnProducts(string prodNum)
        {
            var prodNumParameter = prodNum != null ?
                new ObjectParameter("ProdNum", prodNum) :
                new ObjectParameter("ProdNum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_returnProducts_Result>("sp_returnProducts", prodNumParameter);
        }
    }
}
