//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductMaterials.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int ProdID { get; set; }
        public string ProdNum { get; set; }
        public string ProdCode { get; set; }
        public string ProdDesc { get; set; }
        public Nullable<short> ProdSize { get; set; }
        public Nullable<int> ProdWeight { get; set; }
        public string ProdGrade { get; set; }
        public string ProdPack { get; set; }
        public string Commodity { get; set; }
        public string ProductType { get; set; }
        public byte ProdCompany { get; set; }
        public Nullable<short> CasesPerPallet { get; set; }
        public string Class { get; set; }
        public string MATCATEGORY { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string ManufacturerCode { get; set; }
        public string SpecComments { get; set; }
        public string UPCCODE { get; set; }
        public string UPCCODE2 { get; set; }
    }
}
